@currency  AFN  Afghani
@currency  EUR  Euro
@currency  ALL  Lek
@currency  DZD  AlgerianDinar
@currency  USD  USDollar
@currency  AOA  Kwanza
@currency  XCD  EastCaribbeanDollar
@currency  ARS  ArgentinePeso
@currency  AMD  ArmenianDram
@currency  AWG  ArubanFlorin
@currency  AUD  AustralianDollar
@currency  AZN  AzerbaijanManat
@currency  BSD  BahamianDollar
@currency  BHD  BahrainiDinar
@currency  BDT  Taka
@currency  BBD  BarbadosDollar
@currency  BYN  BelarusianRuble
@currency  BZD  BelizeDollar
@currency  XOF  CFAFrancBCEAO
@currency  BMD  BermudianDollar
@currency  INR  IndianRupee
@currency  BTN  Ngultrum
@currency  BOB  Boliviano
@currency  BOV  Mvdol
@currency  BAM  ConvertibleMark
@currency  BWP  Pula
@currency  NOK  NorwegianKrone
@currency  BRL  BrazilianReal
@currency  BND  BruneiDollar
@currency  BGN  BulgarianLev
@currency  BIF  BurundiFranc
@currency  CVE  CaboVerdeEscudo
@currency  KHR  Riel
@currency  XAF  CFAFrancBEAC
@currency  CAD  CanadianDollar
@currency  KYD  CaymanIslandsDollar
@currency  CLP  ChileanPeso
@currency  CLF  UnidadDeFomento
@currency  CNY  YuanRenminbi
@currency  COP  ColombianPeso
@currency  COU  UnidadDeValorReal
@currency  KMF  ComorianFranc
@currency  CDF  CongoleseFranc
@currency  NZD  NewZealandDollar
@currency  CRC  CostaRicanColon
@currency  HRK  Kuna
@currency  CUP  CubanPeso
@currency  CUC  PesoConvertible
@currency  ANG  NetherlandsAntilleanGuilder
@currency  CZK  CzechKoruna
@currency  DKK  DanishKrone
@currency  DJF  DjiboutiFranc
@currency  DOP  DominicanPeso
@currency  EGP  EgyptianPound
@currency  SVC  ElSalvadorColon
@currency  ERN  Nakfa
@currency  SZL  Lilangeni
@currency  ETB  EthiopianBirr
@currency  FKP  FalklandIslandsPound
@currency  FJD  FijiDollar
@currency  XPF  CFPFranc
@currency  GMD  Dalasi
@currency  GEL  Lari
@currency  GHS  GhanaCedi
@currency  GIP  GibraltarPound
@currency  GTQ  Quetzal
@currency  GBP  PoundSterling
@currency  GNF  GuineanFranc
@currency  GYD  GuyanaDollar
@currency  HTG  Gourde
@currency  HNL  Lempira
@currency  HKD  HongKongDollar
@currency  HUF  Forint
@currency  ISK  IcelandKrona
@currency  IDR  Rupiah
@currency  XDR  SDR(SpecialDrawingRight)
@currency  IRR  IranianRial
@currency  IQD  IraqiDinar
@currency  ILS  NewIsraeliSheqel
@currency  JMD  JamaicanDollar
@currency  JPY  Yen
@currency  JOD  JordanianDinar
@currency  KZT  Tenge
@currency  KES  KenyanShilling
@currency  KPW  NorthKoreanWon
@currency  KRW  Won
@currency  KWD  KuwaitiDinar
@currency  KGS  Som
@currency  LAK  LaoKip
@currency  LBP  LebanesePound
@currency  LSL  Loti
@currency  ZAR  Rand
@currency  LRD  LiberianDollar
@currency  LYD  LibyanDinar
@currency  CHF  SwissFranc
@currency  MOP  Pataca
@currency  MKD  Denar
@currency  MGA  MalagasyAriary
@currency  MWK  MalawiKwacha
@currency  MYR  MalaysianRinggit
@currency  MVR  Rufiyaa
@currency  MRU  Ouguiya
@currency  MUR  MauritiusRupee
@currency  XUA  ADBUnitOfAccount
@currency  MXN  MexicanPeso
@currency  MXV  MexicanUnidadDeInversion(UDI)
@currency  MDL  MoldovanLeu
@currency  MNT  Tugrik
@currency  MAD  MoroccanDirham
@currency  MZN  MozambiqueMetical
@currency  MMK  Kyat
@currency  NAD  NamibiaDollar
@currency  NPR  NepaleseRupee
@currency  NIO  CordobaOro
@currency  NGN  Naira
@currency  OMR  RialOmani
@currency  PKR  PakistanRupee
@currency  PAB  Balboa
@currency  PGK  Kina
@currency  PYG  Guarani
@currency  PEN  Sol
@currency  PHP  PhilippinePeso
@currency  PLN  Zloty
@currency  QAR  QatariRial
@currency  RON  RomanianLeu
@currency  RUB  RussianRuble
@currency  RWF  RwandaFranc
@currency  SHP  SaintHelenaPound
@currency  WST  Tala
@currency  STN  Dobra
@currency  SAR  SaudiRiyal
@currency  RSD  SerbianDinar
@currency  SCR  SeychellesRupee
@currency  SLL  Leone
@currency  SGD  SingaporeDollar
@currency  XSU  Sucre
@currency  SBD  SolomonIslandsDollar
@currency  SOS  SomaliShilling
@currency  SSP  SouthSudanesePound
@currency  LKR  SriLankaRupee
@currency  SDG  SudanesePound
@currency  SRD  SurinamDollar
@currency  SEK  SwedishKrona
@currency  CHE  WIREuro
@currency  CHW  WIRFranc
@currency  SYP  SyrianPound
@currency  TWD  NewTaiwanDollar
@currency  TJS  Somoni
@currency  TZS  TanzanianShilling
@currency  THB  Baht
@currency  TOP  PaAnga
@currency  TTD  TrinidadAndTobagoDollar
@currency  TND  TunisianDinar
@currency  TRY  TurkishLira
@currency  TMT  TurkmenistanNewManat
@currency  UGX  UgandaShilling
@currency  UAH  Hryvnia
@currency  AED  UAEDirham
@currency  USN  USDollar(NextDay)
@currency  UYU  PesoUruguayo
@currency  UYI  UruguayPesoEnUnidadesIndexadas(UI)
@currency  UYW  UnidadPrevisional
@currency  UZS  UzbekistanSum
@currency  VUV  Vatu
@currency  VES  BolívarSoberano
@currency  VND  Dong
@currency  YER  YemeniRial
@currency  ZMW  ZambianKwacha
@currency  ZWL  ZimbabweDollar
@currency  XBA  BondMarketsUnitEuropeanCompositeUnit(EURCO)
@currency  XBB  BondMarketsUnitEuropeanMonetaryUnit(E.M.U.-6)
@currency  XBC  BondMarketsUnitEuropeanUnitOfAccount9(E.U.A.-9)
@currency  XBD  BondMarketsUnitEuropeanUnitOfAccount17(E.U.A.-17)
@currency  XTS  CodesSpecificallyReservedForTestingPurposes
@currency  XXX  TheCodesAssignedForTransactionsWhereNoCurrencyIsInvolved
@currency  XAU  Gold
@currency  XPD  Palladium
@currency  XPT  Platinum
@currency  XAG  Silver
